default: &default
  # browserslist:
  ### defaults to:
  #   - "> 1%"
  #   - "IE 11"

  entries:
    index: "./src/entries/Landing"

  globals:
    devServerPort: 4000
    srcScriptsDir: "./src"
    buildScriptsDir: "./public"

  # proxy:
  #   /api:
  #     target: "https://test-api.bruitt.com"
  #     changeOrigin: true
  #     pathRewrite:
  #       "^/api" : ""

  # prerender: true (defaults to false)
  ### `true` value defaults to:
  # prerender:
  #   routes:
  #     - "/"
  #   options:
  #     ...

  # images: true (defaults to false)
  ### `true` value defaults to:
  # images:
  #   optipng:
  #     optimizationLevel: 7
  #   gifsicle:
  #     interlaced: false
  #   pngquant:
  #     quality: "65-90"
  #     speed: 4
  #   mozjpeg:
  #     quality: 77

  styles:
    # extractCss: true (defaults to true @ prod build)
    # cssMangling: false (defaults to false)
    localIdentName: "ns-[name]-[local]"

  htmls:
    template: "./src/templates/index.html"

  # htmls:
  #   - template: "./src/templates/index.html"
  #     filename: "index.html"
  #     chunks:
  #       - index
  #   - template: "./src/templates/about.html"
  #     filename: "about.html"
  #     chunks:
  #       - about

  # transpilePackages:
  #   - "untranspiledPackageA"
  #   - "untranspiledPackageB"

development:
  <<: *default

production: &production
  <<: *default

  alias:
    "react": "preact-compat"
    "react-dom": "preact-compat"

staging:
  <<: *production
